# Generated by Django 4.2.14 on 2024-09-06 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('units', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Readings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('quantity', models.FloatField()),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('metric', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='Analysis.metric')),
            ],
        ),
    ]
