# Generated by Django 4.2.14 on 2024-09-09 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readings',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='Analysis.metric'),
        ),
    ]
